### ISSUE TITLE
AWS EKS Fargate

### ISSUE THREAD

**Issue by raelga** [raelga/nodeless-kubernetes#4]
- Fargate Virtual-Kubelet provider

https://github.com/virtual-kubelet/aws-fargate

- Fargate Virtual-Kubelet provider in EC2 with Terraform

https://blog.alterway.fr/en/virtual-kubelet-with-aws-eks.html

- AWS "OpenSource" blog post about Virtual Kubelet Fargate provider

https://aws.amazon.com/blogs/opensource/aws-fargate-virtual-kubelet/

- Fargate Virtual-Kubelet agent running in Fargate (Fargateception)

https://github.com/bbrfkr/vk-fargate

**Comment by roivaz** [comment]
Lab tasks:

- [x] Shared VPC
- [x] EKS cluster in shared VPC
- [x] ECS cluster in shared VPC
- [x] ECR repository
- [x] virtual-kubelet image in ECR repository
- [ ] virtual-kubelet ECS task in Fargate mode
- [ ] Assign roles to pods with EKS native integration
- [ ] Study viabilty of deploying an ingress somehow
- [ ] Create slides with elements in each step of the solution
